# This is a basic workflow that is manually triggered

name: Bump version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semver type of new version (major / minor / patch)'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      # Check out the content (source branch).  Use a deploy key so that
      # when we push changes, it will trigger the release workflow
      # run that runs on: tag. (Using the GitHub token would
      # not run the workflow to prevent infinite recursion.)
      - name: Check out source
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Git
        run: |
          git config user.name 'mschuepbach'
          git config user.email 'mschuepbach@pm.me'

      - name: bump version
        run: pnpm version ${{ github.event.inputs.version }}

      - name: Push latest version
        run: git push origin main --follow-tags
